version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gutendex_postgres
    environment:
      POSTGRES_DB: gutendex
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
